apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webservice-dispatcher-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.org/http-method-match: "POST"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: webservicedispatcher
              servicePort: 8080
            path: /wallets/transactions/
            pathType: Exact