spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            deserialization-exception-handler: logandcontinue
            application-id: wallet-materialized-view-processor
      function:
        definition: walletTransactionToCosmoDbView;balanceUpdatedEventToCosmoDbView
      bindings:
        walletTransactionToCosmoDbView-in-0:
          destination: wallet.transactionCreatedEvent
          consumer:
            nativeDecoding: false
        balanceUpdatedEventToCosmoDbView-in-0:
          destination: wallet.balanceUpdatedEvent
          consumer:
            nativeDecoding: false
