spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            deserialization-exception-handler: logandcontinue
      function:
        definition: walletTransactionToCosmoDbView;balanceUpdatedEventToCosmoDbView
      bindings:
        walletTransactionToCosmoDbView-in-0:
          destination: wallet.transactionCreatedEvent
          consumer:
            nativeDecoding: false
        logandcontinue-in-0:
          destination: wallet.balanceUpdatedEvent
          consumer:
            nativeDecoding: false
application:
  cosmosdb:
    accountHost: https://acccosdb.documents.azure.com:443/
    accountKey: 3CWBwopgQeNTYWpCr94kE83lzvlhIAxy6mfjbZ5LmgJfZQzKr2e9149e7QaNK1uZQXIwdH8JbYPok4VLCcIG1Q==
    database: pages-dev
    container: wallet-transaction-e0
---
spring:
    profiles: e0

