spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            deserialization-exception-handler: logandcontinue
      function:
        definition: createTransactionCommandHandler
      bindings:
#        主要輸入
        createTransactionCommandHandler-in-0:
          destination: wallet.createTransactionCommand
          consumer:
            nativeDecoding: false
        createTransactionCommandHandler-out-0:
          destination: wallet.createTransactionCommandProcessedEvent
          consumer:
            nativeDecoding: false

application:
  topic:
    name:
      store: TransactionCreatedEventStore
      out-1: wallet.transactionCreatedEvent
      out-2: wallet.balanceUpdatedEvent