spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            deserialization-exception-handler: logandcontinue
      function:
        definition: createTransactionCommandHandler
      bindings:
#        主要輸入
        createTransactionCommandHandler-in-0:
          destination: wallet.createTransactionCommand
          consumer:
            nativeDecoding: false
        createTransactionCommandHandler-in-1:
          destination: wallet.transactionCreatedEvent
          consumer:
            nativeDecoding: false
        createTransactionCommandHandler-out-0:
          destination: wallet.createTransactionCommandProcessedEvent
          consumer:
            nativeDecoding: false