apiVersion : apps/v1
kind: Deployment
metadata:
  name: walletmaterializedviewprocessor 
spec:
  replicas: 1
  progressDeadlineSeconds: 900
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: walletmaterializedviewprocessor
  template:
    metadata:
      labels:
        app: walletmaterializedviewprocessor 
    spec:
      containers:
        - name: walletmaterializedviewprocessor 
          image: mayortestpags01.azurecr.io/walletmaterializedviewprocessor
          envFrom:
            - configMapRef:
                name: pags-common
      restartPolicy: Always