apiVersion : apps/v1
kind: Deployment
metadata:
  name: wallettransactionprocessor 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallettransactionprocessor
  template:
    metadata:
      labels:
        app: wallettransactionprocessor 
    spec:
      containers:
        - name: wallettransactionprocessor 
          image: dhtpags.azurecr.io/wallettransactionprocessor
          envFrom:
            - configMapRef:
                name: pags-common
          env:
            - name: TZ
              value: Asia/Shanghai
          volumeMounts:
            - name: tz-config
              mountPath: /etc/localtime
      volumes:
        - name: tz-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
      restartPolicy: Always
