apiVersion : apps/v1
kind: Deployment
metadata:
  name: walletmaterializedviewrecordchecker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: walletmaterializedviewrecordchecker
  template:
    metadata:
      labels:
        app: walletmaterializedviewrecordchecker
    spec:
      containers:
        - name: walletmaterializedviewrecordchecker
          image: mayortestpags01.azurecr.io/walletmaterializedviewrecordchecker
          envFrom:
            - configMapRef:
                name: pags-common
      restartPolicy: Always